#!/bin/sh

cd $(dirname $0)
base_url=$(../utility/base_url)

if [ $# -ge 4 ] ; then
    curl \
      --include \
      --request POST  \
      --header "Content-Type: application/json" \
      --data  '{"user_name": "'$1'", "user_email": "'$2'", "user_location": "'$3'", "item": "'$4'", "quantity":'$5' }' \
      $base_url/ask
else
    echo "Usage: ./add_ask name email location item quantity"
fi
