#!/bin/sh

cd $(dirname $0)
base_url=$(../utility/base_url)

if [ $# -ge 1 ] ; then
    curl \
      --include \
      --request PUT \
      --header "Content-Type: application/json" \
      --data  '{"id": "'$1'"}' \
      $base_url/ask/status
else
    echo "Usage: ./fulfill-ask-status id"
fi
