#!/bin/sh

cd $(dirname $0)

./api-calls/asks/add-ask "John" "johndoe@gmail.com" "Water" 3
./api-calls/asks/add-ask "Jeffrey" "jleung513@gmail.com" "Blankets" 1
./api-calls/asks/add-ask "Anmol" "anmol@sfu.ca" "Movers" 1
./api-calls/asks/add-ask "Carol" "cchan@gmail.com" "Socks" 2
./api-calls/asks/add-ask "Carmen" "carmen-yang@gmail.com" "Jackets" 1
./api-calls/asks/add-ask "nwHacks" "nwhacks@gmail.com" "Blankets" 1
./api-calls/asks/add-ask "Darren" "dlevin@gmail.com" "Shirts" 2
